In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
irisDf = pd.read_csv("../../dataset/csv/iris.csv")
irisDf

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [3]:
irisData = pd.DataFrame({'Sepal Length': irisDf['sepal length in cm'], 
                         'Sepal Width': irisDf['sepal width in cm'], 
                         'Class': irisDf['class']})
irisData

     Sepal Length  Sepal Width           Class
0             5.1          3.5     Iris-setosa
1             4.9          3.0     Iris-setosa
2             4.7          3.2     Iris-setosa
3             4.6          3.1     Iris-setosa
4             5.0          3.6     Iris-setosa
..            ...          ...             ...
145           6.7          3.0  Iris-virginica
146           6.3          2.5  Iris-virginica
147           6.5          3.0  Iris-virginica
148           6.2          3.4  Iris-virginica
149           5.9          3.0  Iris-virginica

[150 rows x 3 columns]